export interface CountryInfo {
  code: string;
  name: string;       // native name (shown when app language matches country language)
  englishName: string; // always shown for international users
  flag: string;
  timezone: string;
  language: string;   // i18n dil kodu
}

export const SUPPORTED_COUNTRIES: CountryInfo[] = [
  { code: 'TR', name: 'Türkiye',        englishName: 'Turkey',         flag: '🇹🇷', timezone: 'Europe/Istanbul', language: 'tr' },
  { code: 'GB', name: 'United Kingdom', englishName: 'United Kingdom', flag: '🇬🇧', timezone: 'Europe/London',   language: 'en' },
  { code: 'ES', name: 'España',         englishName: 'Spain',          flag: '🇪🇸', timezone: 'Europe/Madrid',   language: 'es' },
  { code: 'PT', name: 'Portugal',       englishName: 'Portugal',       flag: '🇵🇹', timezone: 'Europe/Lisbon',   language: 'pt' },
  { code: 'FR', name: 'France',         englishName: 'France',         flag: '🇫🇷', timezone: 'Europe/Paris',    language: 'fr' },
  { code: 'DE', name: 'Deutschland',    englishName: 'Germany',        flag: '🇩🇪', timezone: 'Europe/Berlin',   language: 'de' },
  { code: 'IT', name: 'Italia',         englishName: 'Italy',          flag: '🇮🇹', timezone: 'Europe/Rome',     language: 'it' },
  { code: 'SA', name: 'العربية',        englishName: 'Saudi Arabia',   flag: '🇸🇦', timezone: 'Asia/Riyadh',     language: 'ar' },
  { code: 'BR', name: 'Brasil',         englishName: 'Brazil',         flag: '🇧🇷', timezone: 'America/Sao_Paulo',      language: 'pt' },
  { code: 'AR', name: 'Argentina',      englishName: 'Argentina',      flag: '🇦🇷', timezone: 'America/Argentina/Buenos_Aires', language: 'es' },
  { code: 'MX', name: 'México',         englishName: 'Mexico',         flag: '🇲🇽', timezone: 'America/Mexico_City',    language: 'es' },
  { code: 'EG', name: 'مصر',            englishName: 'Egypt',          flag: '🇪🇬', timezone: 'Africa/Cairo',            language: 'ar' },
  { code: 'NG', name: 'Nigeria',        englishName: 'Nigeria',        flag: '🇳🇬', timezone: 'Africa/Lagos',            language: 'en' },
  { code: 'MA', name: 'المغرب',         englishName: 'Morocco',        flag: '🇲🇦', timezone: 'Africa/Casablanca',       language: 'ar' },
  { code: 'SN', name: 'Sénégal',        englishName: 'Senegal',        flag: '🇸🇳', timezone: 'Africa/Dakar',            language: 'fr' },
  // English
  { code: 'US', name: 'United States',  englishName: 'United States',  flag: '🇺🇸', timezone: 'America/New_York',         language: 'en' },
  { code: 'CA', name: 'Canada',         englishName: 'Canada',         flag: '🇨🇦', timezone: 'America/Toronto',          language: 'en' },
  { code: 'AU', name: 'Australia',      englishName: 'Australia',      flag: '🇦🇺', timezone: 'Australia/Sydney',         language: 'en' },
  { code: 'NZ', name: 'New Zealand',    englishName: 'New Zealand',    flag: '🇳🇿', timezone: 'Pacific/Auckland',         language: 'en' },
  { code: 'ZA', name: 'South Africa',   englishName: 'South Africa',   flag: '🇿🇦', timezone: 'Africa/Johannesburg',      language: 'en' },
  { code: 'GH', name: 'Ghana',          englishName: 'Ghana',          flag: '🇬🇭', timezone: 'Africa/Accra',             language: 'en' },
  // German
  { code: 'AT', name: 'Österreich',     englishName: 'Austria',        flag: '🇦🇹', timezone: 'Europe/Vienna',           language: 'de' },
  { code: 'CH', name: 'Schweiz',        englishName: 'Switzerland',    flag: '🇨🇭', timezone: 'Europe/Zurich',           language: 'de' },
  // French
  { code: 'BE', name: 'Belgique',       englishName: 'Belgium',        flag: '🇧🇪', timezone: 'Europe/Brussels',         language: 'fr' },
  // Arabic
  { code: 'QA', name: 'قطر',            englishName: 'Qatar',          flag: '🇶🇦', timezone: 'Asia/Qatar',              language: 'ar' },
  { code: 'AE', name: 'الإمارات',       englishName: 'UAE',            flag: '🇦🇪', timezone: 'Asia/Dubai',              language: 'ar' },
  { code: 'DZ', name: 'الجزائر',        englishName: 'Algeria',        flag: '🇩🇿', timezone: 'Africa/Algiers',          language: 'ar' },
  { code: 'TN', name: 'تونس',           englishName: 'Tunisia',        flag: '🇹🇳', timezone: 'Africa/Tunis',            language: 'ar' },
  // Spanish
  { code: 'CO', name: 'Colombia',       englishName: 'Colombia',       flag: '🇨🇴', timezone: 'America/Bogota',          language: 'es' },
  { code: 'CL', name: 'Chile',          englishName: 'Chile',          flag: '🇨🇱', timezone: 'America/Santiago',        language: 'es' },
  { code: 'UY', name: 'Uruguay',        englishName: 'Uruguay',        flag: '🇺🇾', timezone: 'America/Montevideo',      language: 'es' },
  { code: 'PE', name: 'Perú',           englishName: 'Peru',           flag: '🇵🇪', timezone: 'America/Lima',            language: 'es' },
];

export const COUNTRY_CHANNEL_MAP: Record<string, Record<string, string[]>> = {
  // ─── Türkiye ────────────────────────────────────────────────────────────────
  TR: {
    superlig:      ['beIN Sports 1', 'beIN Sports 2', 'beIN Sports 3', 'TV8', 'A Spor'],
    lig1:          ['TRT Spor', 'beIN Sports 2'],
    lig2:          ['Yaay'],
    champions:     ['beIN Sports MAX', 'beIN Sports 1'],
    europa:        ['beIN Sports 2'],
    conference:    ['beIN Sports 3'],
    premier:       ['beIN Sports 1', 'beIN Sports 4'],
    laliga:        ['Tivibu Spor 2', 'S Sport Plus'],
    bundesliga:    ['S Sport 2', 'S Sport'],
    seriea:        ['beIN Sports 2', 'beIN Sports 3'],
    ligue1:        ['beIN Sports 3'],
    saudi:         ['S Sport Plus'],
    liganos:       ['Tivibu Spor 1', 'S Sport Plus'],
    national:      ['TRT Spor', 'TRT Spor 2', 'TV8'],
    euroleague:    ['S Sport', 'S Sport 2', 'S Sport Plus'],
    eurocup:       ['TRT Spor Yıldız', 'tabii Spor'],
    bsl:           ['HT Spor'],
    nba:           ['NBA TV', 'beIN Sports'],
    efeler:        ['TRT Spor 2', 'Spor Smart'],
    sultansliga:   ['TRT Spor 2', 'Spor Smart'],
    tvfkadin:      ['TRT Spor Yıldız', 'tabii Spor'],
    f1:            ['S Sport 2', 'S Sport'],
  },

  // ─── United Kingdom ─────────────────────────────────────────────────────────
  GB: {
    superlig:    ['TRT World'],
    lig1:        ['TRT World'],
    champions:   ['TNT Sports 1', 'Channel 5'],
    europa:      ['TNT Sports 2', 'Channel 5'],
    conference:  ['TNT Sports 3'],
    premier:     ['Sky Sports Main Event', 'Sky Sports PL', 'TNT Sports 1', 'Amazon Prime'],
    laliga:      ['Sky Sports Football', 'Premier Sports'],
    bundesliga:  ['Sky Sports Football', 'TNT Sports'],
    seriea:      ['TNT Sports 1', 'TNT Sports 2'],
    ligue1:      ['Sky Sports Football'],
    saudi:       ['Sky Sports'],
    liganos:     ['Premier Sports'],
    national:    ['ITV1', 'BBC One'],
    wc2026:      ['ITV1', 'BBC One'],
    euroleague:  ['TNT Sports'],
    eurocup:     ['TNT Sports'],
    bsl:         [],
    nba:         ['Sky Sports Arena', 'TNT Sports'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Sky Sports F1'],
  },

  // ─── España ─────────────────────────────────────────────────────────────────
  ES: {
    superlig:    ['DAZN'],
    lig1:        ['DAZN'],
    champions:   ['Movistar+ Champions', 'DAZN'],
    europa:      ['DAZN', 'Movistar+'],
    conference:  ['DAZN'],
    premier:     ['DAZN', 'Movistar+'],
    laliga:      ['DAZN LaLiga', 'Movistar+ LaLiga'],
    bundesliga:  ['DAZN'],
    seriea:      ['DAZN', 'Movistar+'],
    ligue1:      ['DAZN'],
    saudi:       ['DAZN'],
    liganos:     ['DAZN'],
    national:    ['La 1 (RTVE)', 'Telecinco'],
    wc2026:          ['DAZN'],
    wc2026_spain:    ['La 1 (RTVE)', 'Cuatro', 'DAZN'],
    euroleague:  ['DAZN'],
    eurocup:     ['DAZN'],
    bsl:         [],
    nba:         ['Movistar+', 'DAZN'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['DAZN F1'],
  },

  // ─── Portugal ───────────────────────────────────────────────────────────────
  PT: {
    superlig:    ['Sport TV+'],
    lig1:        ['Sport TV+'],
    champions:   ['Sport TV 1', 'RTP 1'],
    europa:      ['Sport TV 1'],
    conference:  ['Sport TV 2'],
    premier:     ['Sport TV 1', 'Sport TV 2'],
    laliga:      ['Sport TV 3'],
    bundesliga:  ['Sport TV 4'],
    seriea:      ['Sport TV 2'],
    ligue1:      ['Sport TV 3'],
    saudi:       ['Sport TV'],
    liganos:     ['Sport TV 1', 'Sport TV 2'],
    national:    ['RTP 1', 'SIC'],
    wc2026:      ['RTP 1', 'SIC', 'Sport TV'],
    euroleague:  ['Sport TV'],
    eurocup:     ['Sport TV'],
    bsl:         [],
    nba:         ['Sport TV'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Canal+', 'Sport TV'],
  },

  // ─── France ─────────────────────────────────────────────────────────────────
  FR: {
    superlig:    ['beIN Sports 1'],
    lig1:        ['beIN Sports 1'],
    champions:   ['Canal+', 'M6', 'TF1'],
    europa:      ['Canal+', 'beIN Sports'],
    conference:  ['Canal+'],
    premier:     ['Canal+'],
    laliga:      ['Canal+', 'beIN Sports 1'],
    bundesliga:  ['Canal+', 'beIN Sports 1'],
    seriea:      ['Canal+', 'beIN Sports 1'],
    ligue1:      ['DAZN 1', 'DAZN 2', 'beIN Sports 1', 'Canal+'],
    saudi:       ['beIN Sports'],
    liganos:     ['Canal+'],
    national:    ['TF1', 'France 2'],
    wc2026:             ['beIN Sports', 'M6', 'TF1'],
    wc2026_france:      ['M6', 'beIN Sports'],
    wc2026_cotedivoire: ['beIN Sports'],
    euroleague:  ['beIN Sports'],
    eurocup:     ['beIN Sports'],
    bsl:         [],
    nba:         ['beIN Sports'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Canal+'],
  },

  // ─── Deutschland ────────────────────────────────────────────────────────────
  DE: {
    superlig:    ['DAZN'],
    lig1:        ['DAZN'],
    champions:   ['DAZN', 'Amazon Prime', 'ZDF'],
    europa:      ['RTL', 'DAZN'],
    conference:  ['DAZN'],
    premier:     ['Sky Sport', 'DAZN'],
    laliga:      ['DAZN', 'Sky Sport'],
    bundesliga:  ['Sky Sport Bundesliga', 'DAZN', 'SAT.1'],
    seriea:      ['DAZN', 'Sky Sport'],
    ligue1:      ['DAZN'],
    saudi:       ['DAZN'],
    liganos:     ['DAZN'],
    national:    ['ARD', 'ZDF', 'RTL'],
    wc2026:      ['ARD', 'ZDF', 'RTL'],
    euroleague:  ['MagentaSport'],
    eurocup:     ['MagentaSport'],
    bsl:         [],
    nba:         ['Sky Sport'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['RTL', 'Sky Sport F1'],
  },

  // ─── Italia ─────────────────────────────────────────────────────────────────
  IT: {
    superlig:    ['Sky Sport', 'DAZN'],
    lig1:        ['DAZN'],
    champions:   ['Canale 5', 'Sky Sport', 'Amazon Prime'],
    europa:      ['Sky Sport', 'TV8'],
    conference:  ['Sky Sport', 'TV8'],
    premier:     ['Sky Sport Football'],
    laliga:      ['DAZN', 'Sky Sport'],
    bundesliga:  ['Sky Sport', 'DAZN'],
    seriea:      ['DAZN', 'Sky Sport Calcio'],
    ligue1:      ['Sky Sport', 'DAZN'],
    saudi:       ['DAZN'],
    liganos:     ['DAZN'],
    national:    ['RAI 1', 'RAI 2'],
    wc2026:      ['DAZN', 'RAI 1'],
    euroleague:  ['Sky Sport'],
    eurocup:     ['Sky Sport'],
    bsl:         [],
    nba:         ['Sky Sport'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Sky Sport F1'],
  },

  // ─── Arapça / Orta Doğu (Suudi Arabistan) ───────────────────────────────────
  SA: {
    superlig:    ['beIN Sports Arabia 1'],
    lig1:        ['beIN Sports Arabia'],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia HD 1'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1', 'beIN Sports Arabia 2'],
    laliga:      ['beIN Sports Arabia 2', 'beIN Sports Arabia 3'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4'],
    saudi:       ['SSC Sport 1', 'SSC Sport 2'],
    liganos:     ['beIN Sports Arabia'],
    national:    ['beIN Sports Arabia 1', 'MBC Sport 1'],
    wc2026:      ['beIN Sports Arabia 1', 'MBC Sport 1'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     ['beIN Sports Arabia'],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia'],
  },

  // ─── Brasil ─────────────────────────────────────────────────────────────────
  BR: {
    superlig:    ['ESPN', 'DAZN'],
    lig1:        [],
    champions:   ['SBT', 'TNT Sports', 'Max', 'ESPN'],
    europa:      ['ESPN', 'TNT Sports'],
    conference:  ['DAZN'],
    premier:     ['ESPN', 'Star+'],
    laliga:      ['ESPN', 'Star+'],
    bundesliga:  ['OneFootball', 'DAZN'],
    seriea:      ['ESPN', 'Star+'],
    ligue1:      ['CazéTV', 'DAZN'],
    saudi:       ['DAZN'],
    liganos:     [],
    national:    ['Globo', 'SporTV', 'Band'],
    wc2026:      ['Globo', 'SporTV', 'CazéTV', 'Band'],
    brasileirao: ['Globo', 'SporTV', 'Cazé TV', 'Amazon Prime'],
    euroleague:  ['ESPN'],
    eurocup:     ['ESPN'],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass', 'Max'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Globo', 'Band', 'F1 TV'],
  },

  // ─── Argentina ──────────────────────────────────────────────────────────────
  AR: {
    superlig:    ['DirecTV Sports', 'ESPN'],
    lig1:        [],
    champions:   ['ESPN', 'Fox Sports', 'TNT Sports'],
    europa:      ['ESPN', 'Fox Sports'],
    conference:  ['ESPN'],
    premier:     ['ESPN', 'Star+'],
    laliga:      ['ESPN', 'Star+'],
    bundesliga:  ['DirecTV Sports', 'ESPN'],
    seriea:      ['ESPN', 'Star+'],
    ligue1:      ['ESPN', 'Star+'],
    saudi:       ['DirecTV Sports'],
    liganos:     [],
    national:    ['TyC Sports', 'TV Pública', 'Canal 9'],
    wc2026:      ['TyC Sports', 'TV Pública', 'DirecTV Sports'],
    ligaprofesional: ['TNT Sports', 'ESPN', 'TyC Sports'],
    euroleague:  ['ESPN'],
    eurocup:     ['ESPN'],
    bsl:         [],
    nba:         ['NBA League Pass', 'ESPN', 'DirecTV Sports'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['ESPN', 'Fox Sports'],
  },

  // ─── México ─────────────────────────────────────────────────────────────────
  MX: {
    superlig:    ['DAZN', 'DirecTV Sports'],
    lig1:        [],
    champions:   ['Max', 'TUDN', 'Canal 5'],
    europa:      ['TUDN', 'ESPN'],
    conference:  ['DAZN'],
    premier:     ['ESPN', 'Star+', 'Sky Sports'],
    laliga:      ['ESPN', 'Sky Sports'],
    bundesliga:  ['DAZN', 'Sky Sports'],
    seriea:      ['ESPN', 'Sky Sports'],
    ligue1:      ['DAZN'],
    saudi:       ['DAZN'],
    liganos:     [],
    national:    ['Azteca', 'TUDN', 'Canal 5'],
    wc2026:      ['TV Azteca', 'TUDN', 'Canal 5'],
    ligamx:      ['TUDN', 'Fox Sports', 'Azteca Deportes', 'Canal 5'],
    euroleague:  ['ESPN'],
    eurocup:     ['ESPN'],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass', 'Sky Sports'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Sky Sports', 'ESPN', 'TUDN'],
  },

  // ─── Mısır ──────────────────────────────────────────────────────────────────
  EG: {
    superlig:    ['beIN Sports Arabia 1'],
    lig1:        [],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia 2'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1'],
    laliga:      ['beIN Sports Arabia 2'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4'],
    saudi:       ['beIN Sports Arabia'],
    liganos:     ['beIN Sports Arabia'],
    national:    ['ON Sport', 'Al Kahera Wal Nas', 'CBC Sport'],
    wc2026:      ['beIN Sports Arabia 1', 'ON Sport'],
    premiereg:   ['ON Sport', 'beIN Sports Arabia'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     [],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia'],
  },

  // ─── Nigeria ────────────────────────────────────────────────────────────────
  NG: {
    superlig:    ['SuperSport', 'DSTV'],
    lig1:        [],
    champions:   ['SuperSport', 'DSTV', 'CNN Sport'],
    europa:      ['SuperSport', 'DSTV'],
    conference:  ['SuperSport'],
    premier:     ['SuperSport Premier League', 'DSTV'],
    laliga:      ['SuperSport', 'DSTV'],
    bundesliga:  ['SuperSport', 'DSTV'],
    seriea:      ['SuperSport', 'DSTV'],
    ligue1:      ['SuperSport'],
    saudi:       ['SuperSport'],
    liganos:     [],
    national:    ['NTA Sports', 'SuperSport', 'Africa Magic'],
    wc2026:      ['SuperSport', 'NTA Sports', 'DSTV'],
    euroleague:  ['SuperSport'],
    eurocup:     [],
    bsl:         [],
    nba:         ['SuperSport', 'DSTV'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['SuperSport', 'DSTV'],
  },

  // ─── Fas / Maroc ────────────────────────────────────────────────────────────
  MA: {
    superlig:    ['beIN Sports Arabia 1'],
    lig1:        [],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia 2', '2M'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1', 'Canal+'],
    laliga:      ['beIN Sports Arabia 2', 'Canal+'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4', 'Canal+'],
    saudi:       ['beIN Sports Arabia'],
    liganos:     [],
    national:    ['2M', 'Arryadia', 'Al Aoula'],
    wc2026:      ['2M', 'Arryadia', 'beIN Sports Arabia'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     [],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia', 'Canal+'],
  },

  // ─── Sénégal ────────────────────────────────────────────────────────────────
  SN: {
    superlig:    ['Canal+ Afrique'],
    lig1:        [],
    champions:   ['Canal+ Afrique', 'RTS'],
    europa:      ['Canal+ Afrique'],
    conference:  ['Canal+ Afrique'],
    premier:     ['Canal+ Afrique'],
    laliga:      ['Canal+ Afrique'],
    bundesliga:  ['Canal+ Afrique'],
    seriea:      ['Canal+ Afrique'],
    ligue1:      ['Canal+ Afrique'],
    saudi:       ['Canal+ Afrique'],
    liganos:     [],
    national:    ['RTS', 'TFM', 'Canal+ Afrique'],
    wc2026:      ['RTS 1', 'Canal+ Afrique'],
    euroleague:  ['Canal+ Afrique'],
    eurocup:     [],
    bsl:         [],
    nba:         ['Canal+ Afrique'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Canal+ Afrique'],
  },

  // ─── United States ──────────────────────────────────────────────────────────
  US: {
    superlig:    [],
    lig1:        [],
    champions:   ['Paramount+', 'CBS Sports', 'TUDN'],
    europa:      ['Paramount+', 'CBS Sports'],
    conference:  ['Paramount+'],
    premier:     ['Peacock', 'NBC Sports', 'USA Network'],
    laliga:      ['ESPN+', 'ABC'],
    bundesliga:  ['ESPN+', 'ESPN'],
    seriea:      ['Paramount+', 'CBS Sports'],
    ligue1:      ['beIN Sports', 'CBS Sports'],
    saudi:       ['ESPN+'],
    liganos:     ['Paramount+'],
    national:    ['Fox Sports 1', 'FS1', 'Telemundo', 'TNT'],
    wc2026:      ['Fox Sports', 'FS1', 'Telemundo', 'TNT'],
    euroleague:  ['ESPN+'],
    eurocup:     ['ESPN+'],
    bsl:         [],
    nba:         ['ESPN', 'ABC', 'NBA TV'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['ESPN', 'ESPN+'],
  },

  // ─── Canada ─────────────────────────────────────────────────────────────────
  CA: {
    superlig:    [],
    lig1:        [],
    champions:   ['DAZN'],
    europa:      ['DAZN'],
    conference:  ['DAZN'],
    premier:     ['DAZN', 'TSN'],
    laliga:      ['DAZN'],
    bundesliga:  ['DAZN'],
    seriea:      ['DAZN'],
    ligue1:      ['DAZN'],
    saudi:       ['DAZN'],
    liganos:     ['DAZN'],
    national:    ['TSN', 'CTV', 'CBC'],
    wc2026:      ['CTV', 'TSN', 'RDS', 'TVA Sports'],
    euroleague:  ['DAZN'],
    eurocup:     ['DAZN'],
    bsl:         [],
    nba:         ['TSN', 'Sportsnet', 'NBA TV Canada'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['TSN', 'RDS'],
  },

  // ─── Australia ──────────────────────────────────────────────────────────────
  AU: {
    superlig:    [],
    lig1:        [],
    champions:   ['Stan Sport', 'Paramount+'],
    europa:      ['Stan Sport'],
    conference:  ['Stan Sport'],
    premier:     ['Optus Sport', 'beIN Sports'],
    laliga:      ['Optus Sport', 'beIN Sports'],
    bundesliga:  ['Optus Sport'],
    seriea:      ['Paramount+', 'beIN Sports'],
    ligue1:      ['beIN Sports', 'Optus Sport'],
    saudi:       ['beIN Sports'],
    liganos:     ['Optus Sport'],
    national:    ['Network 10', 'SBS', 'Paramount+'],
    wc2026:      ['SBS', 'Optus Sport'],
    euroleague:  ['Stan Sport'],
    eurocup:     ['Stan Sport'],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Fox Sports', 'Channel 10'],
  },

  // ─── New Zealand ────────────────────────────────────────────────────────────
  NZ: {
    superlig:    [],
    lig1:        [],
    champions:   ['Sky Sport'],
    europa:      ['Sky Sport'],
    conference:  ['Sky Sport'],
    premier:     ['Sky Sport'],
    laliga:      ['Sky Sport'],
    bundesliga:  ['Sky Sport'],
    seriea:      ['Sky Sport'],
    ligue1:      ['Sky Sport'],
    saudi:       ['Sky Sport'],
    liganos:     [],
    national:    ['TVNZ', 'Sky Sport'],
    wc2026:      ['Sky Sport', 'TVNZ'],
    euroleague:  ['Sky Sport'],
    eurocup:     [],
    bsl:         [],
    nba:         ['Sky Sport'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Sky Sport'],
  },

  // ─── South Africa ───────────────────────────────────────────────────────────
  ZA: {
    superlig:    [],
    lig1:        [],
    champions:   ['SuperSport', 'DSTV'],
    europa:      ['SuperSport', 'DSTV'],
    conference:  ['SuperSport'],
    premier:     ['SuperSport Premier League', 'DSTV'],
    laliga:      ['SuperSport', 'DSTV'],
    bundesliga:  ['SuperSport', 'DSTV'],
    seriea:      ['SuperSport', 'DSTV'],
    ligue1:      ['SuperSport'],
    saudi:       ['SuperSport'],
    liganos:     [],
    national:    ['SABC Sport', 'SuperSport'],
    wc2026:      ['SABC 1', 'SuperSport', 'DSTV'],
    euroleague:  ['SuperSport'],
    eurocup:     [],
    bsl:         [],
    nba:         ['SuperSport', 'DSTV'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['SuperSport', 'DSTV'],
  },

  // ─── Ghana ──────────────────────────────────────────────────────────────────
  GH: {
    superlig:    [],
    lig1:        [],
    champions:   ['SuperSport', 'DSTV'],
    europa:      ['SuperSport'],
    conference:  ['SuperSport'],
    premier:     ['SuperSport', 'DSTV'],
    laliga:      ['SuperSport'],
    bundesliga:  ['SuperSport'],
    seriea:      ['SuperSport'],
    ligue1:      ['SuperSport'],
    saudi:       ['SuperSport'],
    liganos:     [],
    national:    ['GTV Sports+', 'SuperSport'],
    wc2026:      ['GTV Sports+', 'SuperSport'],
    euroleague:  ['SuperSport'],
    eurocup:     [],
    bsl:         [],
    nba:         ['SuperSport'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['SuperSport'],
  },

  // ─── Austria ────────────────────────────────────────────────────────────────
  AT: {
    superlig:    [],
    lig1:        [],
    champions:   ['DAZN'],
    europa:      ['DAZN', 'ServusTV'],
    conference:  ['DAZN'],
    premier:     ['Sky Austria', 'DAZN'],
    laliga:      ['DAZN', 'Sky Austria'],
    bundesliga:  ['Sky Austria', 'DAZN'],
    seriea:      ['DAZN', 'Sky Austria'],
    ligue1:      ['DAZN'],
    saudi:       ['DAZN'],
    liganos:     [],
    national:    ['ORF 1', 'ORF 2', 'ATV'],
    wc2026:      ['ORF 1', 'ORF 2', 'ServusTV'],
    euroleague:  ['MagentaSport', 'DAZN'],
    eurocup:     ['MagentaSport'],
    bsl:         [],
    nba:         ['Sky Austria'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['ServusTV', 'Sky Sport F1'],
  },

  // ─── Switzerland ────────────────────────────────────────────────────────────
  CH: {
    superlig:    [],
    lig1:        [],
    champions:   ['Blue Sport', 'SRF zwei', 'RTS 2'],
    europa:      ['Blue Sport', 'SRF'],
    conference:  ['Blue Sport'],
    premier:     ['Blue Sport'],
    laliga:      ['Blue Sport', 'DAZN'],
    bundesliga:  ['SRF zwei', 'Blue Sport', 'DAZN'],
    seriea:      ['Blue Sport', 'DAZN'],
    ligue1:      ['Blue Sport', 'RTS'],
    saudi:       ['Blue Sport'],
    liganos:     [],
    national:    ['SRF 1', 'RTS 1', 'RSI La 1'],
    wc2026:      ['SRF 1', 'RTS 1', 'RSI La 1'],
    euroleague:  ['Blue Sport'],
    eurocup:     ['Blue Sport'],
    bsl:         [],
    nba:         ['Blue Sport'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['SRF zwei', 'Blue Sport'],
  },

  // ─── Belgium ────────────────────────────────────────────────────────────────
  BE: {
    superlig:    [],
    lig1:        [],
    champions:   ['RTL TVI', 'Club RTL', 'RTBF'],
    europa:      ['Club RTL', 'RTBF'],
    conference:  ['Play Sports'],
    premier:     ['Play Sports', 'Club RTL'],
    laliga:      ['Play Sports', 'RTBF'],
    bundesliga:  ['Play Sports', 'DAZN'],
    seriea:      ['Play Sports', 'DAZN'],
    ligue1:      ['RTBF Sport', 'Club RTL'],
    saudi:       ['Play Sports'],
    liganos:     [],
    national:    ['RTBF La Une', 'VRT 1'],
    wc2026:      ['RTBF La Une', 'VRT 1', 'RTL TVI'],
    euroleague:  ['RTBF', 'Club RTL'],
    eurocup:     [],
    bsl:         [],
    nba:         ['Play Sports'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['RTBF', 'Sporza'],
  },

  // ─── Qatar ──────────────────────────────────────────────────────────────────
  QA: {
    superlig:    [],
    lig1:        [],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia HD 1'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1', 'beIN Sports Arabia 2'],
    laliga:      ['beIN Sports Arabia 2', 'beIN Sports Arabia 3'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4'],
    saudi:       ['beIN Sports Arabia'],
    liganos:     ['beIN Sports Arabia'],
    national:    ['beIN Sports Arabia 1', 'Al Kass TV'],
    wc2026:      ['beIN Sports Arabia', 'Al Kass TV', 'Qatar TV'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     [],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia'],
  },

  // ─── UAE ────────────────────────────────────────────────────────────────────
  AE: {
    superlig:    [],
    lig1:        [],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia HD 1'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1', 'AD Sports'],
    laliga:      ['beIN Sports Arabia 2'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4'],
    saudi:       ['AD Sports 1', 'AD Sports 2'],
    liganos:     ['beIN Sports Arabia'],
    national:    ['AD Sports', 'beIN Sports Arabia 1'],
    wc2026:      ['AD Sports', 'beIN Sports Arabia', 'Dubai TV'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     [],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia', 'AD Sports'],
  },

  // ─── Algeria ────────────────────────────────────────────────────────────────
  DZ: {
    superlig:    [],
    lig1:        [],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia 2'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1'],
    laliga:      ['beIN Sports Arabia 2'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4', 'Canal+ Algérie'],
    saudi:       ['beIN Sports Arabia'],
    liganos:     [],
    national:    ['ENTV', 'Canal Algérie', 'A3 Sport'],
    wc2026:      ['ENTV', 'A3 Sport', 'beIN Sports Arabia'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     [],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia'],
  },

  // ─── Tunisia ────────────────────────────────────────────────────────────────
  TN: {
    superlig:    [],
    lig1:        [],
    champions:   ['beIN Sports Arabia 1', 'beIN Sports Arabia 2'],
    europa:      ['beIN Sports Arabia 2'],
    conference:  ['beIN Sports Arabia 3'],
    premier:     ['beIN Sports Arabia 1'],
    laliga:      ['beIN Sports Arabia 2'],
    bundesliga:  ['beIN Sports Arabia 3'],
    seriea:      ['beIN Sports Arabia 2'],
    ligue1:      ['beIN Sports Arabia 4', 'Canal+ Tunisie'],
    saudi:       ['beIN Sports Arabia'],
    liganos:     [],
    national:    ['Watania 1', 'Hannibal TV', 'EL Hiwar Ettounsi'],
    wc2026:      ['Watania 1', 'Hannibal TV', 'beIN Sports Arabia'],
    euroleague:  ['beIN Sports Arabia'],
    eurocup:     [],
    bsl:         [],
    nba:         ['beIN Sports Arabia'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['beIN Sports Arabia'],
  },

  // ─── Colombia ───────────────────────────────────────────────────────────────
  CO: {
    superlig:    [],
    lig1:        [],
    champions:   ['ESPN', 'Fox Sports', 'TNT Sports'],
    europa:      ['ESPN', 'Fox Sports'],
    conference:  ['ESPN'],
    premier:     ['ESPN', 'Star+'],
    laliga:      ['ESPN', 'Star+'],
    bundesliga:  ['ESPN', 'Star+'],
    seriea:      ['ESPN', 'Star+'],
    ligue1:      ['ESPN', 'Star+'],
    saudi:       ['DirecTV Sports'],
    liganos:     ['DirecTV Sports', 'ESPN'],
    national:    ['Caracol TV', 'RCN', 'Win Sports'],
    wc2026:      ['Caracol TV', 'RCN', 'DirecTV Sports'],
    euroleague:  ['ESPN'],
    eurocup:     [],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Fox Sports', 'ESPN'],
  },

  // ─── Chile ──────────────────────────────────────────────────────────────────
  CL: {
    superlig:    [],
    lig1:        [],
    champions:   ['ESPN', 'Fox Sports', 'TNT Sports'],
    europa:      ['ESPN', 'Fox Sports'],
    conference:  ['ESPN'],
    premier:     ['ESPN', 'Star+'],
    laliga:      ['ESPN', 'Star+'],
    bundesliga:  ['ESPN', 'Star+'],
    seriea:      ['ESPN', 'Star+'],
    ligue1:      ['ESPN', 'Star+'],
    saudi:       ['DirecTV Sports'],
    liganos:     ['ESPN', 'Fox Sports'],
    national:    ['Canal 13', 'TVN', 'CHV'],
    wc2026:      ['Canal 13', 'TVN', 'DirecTV Sports'],
    euroleague:  ['ESPN'],
    eurocup:     [],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Fox Sports', 'ESPN'],
  },

  // ─── Uruguay ────────────────────────────────────────────────────────────────
  UY: {
    superlig:    [],
    lig1:        [],
    champions:   ['ESPN', 'Fox Sports', 'TyC Sports'],
    europa:      ['ESPN', 'Fox Sports'],
    conference:  ['ESPN'],
    premier:     ['ESPN', 'Star+'],
    laliga:      ['ESPN', 'Star+'],
    bundesliga:  ['ESPN', 'Star+'],
    seriea:      ['ESPN', 'Star+'],
    ligue1:      ['ESPN', 'Star+'],
    saudi:       ['DirecTV Sports'],
    liganos:     ['ESPN', 'TyC Sports'],
    national:    ['Canal 10', 'TCC', 'Canal 4'],
    wc2026:      ['Canal 10', 'TyC Sports', 'DirecTV Sports'],
    euroleague:  ['ESPN'],
    eurocup:     [],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Fox Sports', 'ESPN'],
  },

  // ─── Peru ───────────────────────────────────────────────────────────────────
  PE: {
    superlig:    [],
    lig1:        [],
    champions:   ['ESPN', 'Fox Sports', 'TNT Sports'],
    europa:      ['ESPN', 'Fox Sports'],
    conference:  ['ESPN'],
    premier:     ['ESPN', 'Star+'],
    laliga:      ['ESPN', 'Star+'],
    bundesliga:  ['ESPN', 'Star+'],
    seriea:      ['ESPN', 'Star+'],
    ligue1:      ['ESPN', 'Star+'],
    saudi:       ['DirecTV Sports'],
    liganos:     ['ESPN', 'Fox Sports'],
    national:    ['América TV', 'ATV', 'Latina'],
    wc2026:      ['América TV', 'DirecTV Sports', 'Movistar Deportes'],
    euroleague:  ['ESPN'],
    eurocup:     [],
    bsl:         [],
    nba:         ['ESPN', 'NBA League Pass'],
    efeler:      [],
    sultansliga: [],
    tvfkadin:    [],
    f1:          ['Fox Sports', 'ESPN'],
  },
};

export function getChannelForCountry(
  countryCode: string,
  leagueId: string,
  homeTeamId?: string,
  awayTeamId?: string,
): string {
  const countryMap = COUNTRY_CHANNEL_MAP[countryCode] ?? COUNTRY_CHANNEL_MAP['TR'];
  const channels = countryMap[leagueId] ?? [];

  // Türkiye Süper Lig rotasyonu
  if (leagueId === 'superlig' && countryCode === 'TR') {
    if (homeTeamId === 'galatasaray' || homeTeamId === 'fenerbahce') return 'beIN Sports 1';
    if (homeTeamId === 'besiktas' || homeTeamId === 'trabzonspor') return 'beIN Sports 2';
    const freeTeams = ['adanademirspor', 'gaziantepfk', 'eyupspor', 'rizespor',
                       'sivasspor', 'kayserispor', 'ankaragucu'];
    if (homeTeamId && freeTeams.includes(homeTeamId)) return 'TV8';
  }

  // Ev sahibi takım bazlı özel kanal (ör. GB'de WC maçları ITV/BBC arası bölünmüş, ES'de Spain→La 1)
  if (homeTeamId) {
    const specific = countryMap[`${leagueId}_${homeTeamId}`]?.[0];
    if (specific) return specific;
  }

  // Deplasman takım bazlı özel kanal (ör. ES'de Spain away→La 1)
  if (awayTeamId) {
    const specific = countryMap[`${leagueId}_${awayTeamId}`]?.[0];
    if (specific) return specific;
  }

  return channels[0] ?? '';
}

export function getAllChannelsForCountry(countryCode: string, leagueId: string): string[] {
  const countryMap = COUNTRY_CHANNEL_MAP[countryCode] ?? COUNTRY_CHANNEL_MAP['TR'];
  return countryMap[leagueId] ?? [];
}

export function guessCountryFromLanguage(langCode: string): string {
  const map: Record<string, string> = {
    tr: 'TR',
    en: 'GB',
    es: 'ES',
    pt: 'BR',   // Português listede 🇧🇷 ile gösteriliyor
    fr: 'FR',
    de: 'DE',
    it: 'IT',
    ar: 'SA',
    // Bölgesel dil etiketleri
    'pt-BR': 'BR',
    'es-AR': 'AR',
    'es-MX': 'MX',
    'ar-EG': 'EG',
    'ar-MA': 'MA',
    'fr-SN': 'SN',
    'en-NG': 'NG',
  };
  return map[langCode] ?? map[langCode.split('-')[0]] ?? 'TR';
}

export function getLanguageForCountry(countryCode: string): string {
  return SUPPORTED_COUNTRIES.find((c) => c.code === countryCode)?.language ?? 'tr';
}

export function getTimezoneForCountry(countryCode: string): string {
  return SUPPORTED_COUNTRIES.find((c) => c.code === countryCode)?.timezone ?? 'Europe/Istanbul';
}
