export interface Team {
  id: string;
  name: string;
  nameLocal: Record<string, string>;
  league: string;
  leagueId: string;
  country: string;
  emoji: string;
  color: string;
  sport?: 'football' | 'basketball' | 'volleyball' | 'motorsport';
}

export const LEAGUES = [
  // Futbol
  { id: 'superlig',   name: 'Süper Lig',           emoji: '🇹🇷',  country: 'Turkey',  countryCode: 'TR', sport: 'football' },
  { id: 'premier',    name: 'Premier League',       emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', country: 'England', countryCode: 'GB', sport: 'football' },
  { id: 'laliga',     name: 'La Liga',              emoji: '🇪🇸',  country: 'Spain',   countryCode: 'ES', sport: 'football' },
  { id: 'bundesliga', name: 'Bundesliga',           emoji: '🇩🇪',  country: 'Germany', countryCode: 'DE', sport: 'football' },
  { id: 'seriea',     name: 'Serie A',              emoji: '🇮🇹',  country: 'Italy',   countryCode: 'IT', sport: 'football' },
  { id: 'ligue1',     name: 'Ligue 1',              emoji: '🇫🇷',  country: 'France',  countryCode: 'FR', sport: 'football' },
  { id: 'champions',  name: 'Şampiyonlar Ligi',     emoji: '🏆',  country: 'Europe',  countryCode: null, sport: 'football' },
  { id: 'national',   name: 'Milli Takımlar',       emoji: '🌍',  country: 'World',   countryCode: null, sport: 'football' },
  // Basketbol
  { id: 'nba',        name: 'NBA',                  emoji: '🏀',  country: 'USA',     countryCode: 'US', sport: 'basketball' },
  { id: 'euroleague', name: 'EuroLeague',           emoji: '🏀',  country: 'Europe',  countryCode: null, sport: 'basketball' },
  { id: 'bsl',        name: 'BSL (Basketbol)',       emoji: '🏀',  country: 'Turkey',  countryCode: 'TR', sport: 'basketball' },
  // Voleybol
  { id: 'efeler',       name: 'Efeler Ligi (E)',    emoji: '🏐',  country: 'Turkey',  countryCode: 'TR', sport: 'volleyball' },
  { id: 'sultansliga',  name: 'Sultansliga (K)',     emoji: '🏐',  country: 'Turkey',  countryCode: 'TR', sport: 'volleyball' },
  // Motor sporları
  { id: 'f1',         name: 'Formula 1',            emoji: '🏎️',  country: 'World',   countryCode: null, sport: 'motorsport' },
];

export const TEAMS: Team[] = [
  // ===================== SÜPER LİG =====================
  {
    id: 'galatasaray',
    name: 'Galatasaray',
    nameLocal: { tr: 'Galatasaray', en: 'Galatasaray', es: 'Galatasaray', pt: 'Galatasaray', fr: 'Galatasaray', de: 'Galatasaray', ar: 'غلطة سراي', it: 'Galatasaray' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🦁',
    color: '#FFC107',
  },
  {
    id: 'fenerbahce',
    name: 'Fenerbahçe',
    nameLocal: { tr: 'Fenerbahçe', en: 'Fenerbahce', es: 'Fenerbahçe', pt: 'Fenerbahçe', fr: 'Fenerbahçe', de: 'Fenerbahçe', ar: 'فنربخشة', it: 'Fenerbahçe' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '⚡',
    color: '#FFDD00',
  },
  {
    id: 'besiktas',
    name: 'Beşiktaş',
    nameLocal: { tr: 'Beşiktaş', en: 'Besiktas', es: 'Beşiktaş', pt: 'Beşiktaş', fr: 'Beşiktaş', de: 'Beşiktaş', ar: 'بشيكتاش', it: 'Beşiktaş' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🦅',
    color: '#000000',
  },
  {
    id: 'trabzonspor',
    name: 'Trabzonspor',
    nameLocal: { tr: 'Trabzonspor', en: 'Trabzonspor', es: 'Trabzonspor', pt: 'Trabzonspor', fr: 'Trabzonspor', de: 'Trabzonspor', ar: 'طرابزون', it: 'Trabzonspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🌊',
    color: '#8B0000',
  },
  {
    id: 'basaksehir',
    name: 'Başakşehir',
    nameLocal: { tr: 'Başakşehir', en: 'Istanbul Basaksehir', es: 'Başakşehir', pt: 'Başakşehir', fr: 'Başakşehir', de: 'Başakşehir', ar: 'باشاك شهير', it: 'Başakşehir' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🌟',
    color: '#FF6600',
  },
  {
    id: 'konyaspor',
    name: 'Konyaspor',
    nameLocal: { tr: 'Konyaspor', en: 'Konyaspor', es: 'Konyaspor', pt: 'Konyaspor', fr: 'Konyaspor', de: 'Konyaspor', ar: 'قونيا سبور', it: 'Konyaspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🟢',
    color: '#006400',
  },
  {
    id: 'alanyaspor',
    name: 'Alanyaspor',
    nameLocal: { tr: 'Alanyaspor', en: 'Alanyaspor', es: 'Alanyaspor', pt: 'Alanyaspor', fr: 'Alanyaspor', de: 'Alanyaspor', ar: 'ألانياسبور', it: 'Alanyaspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🟠',
    color: '#FF4500',
  },
  {
    id: 'kasimpasa',
    name: 'Kasımpaşa',
    nameLocal: { tr: 'Kasımpaşa', en: 'Kasimpasa', es: 'Kasımpaşa', pt: 'Kasımpaşa', fr: 'Kasımpaşa', de: 'Kasımpaşa', ar: 'قاسم باشا', it: 'Kasımpaşa' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🔵',
    color: '#0000CD',
  },
  {
    id: 'ankaragucu',
    name: 'Ankaragücü',
    nameLocal: { tr: 'Ankaragücü', en: 'Ankaragucu', es: 'Ankaragücü', pt: 'Ankaragücü', fr: 'Ankaragücü', de: 'Ankaragücü', ar: 'أنقرة جوجو', it: 'Ankaragücü' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '⚓',
    color: '#1C2951',
  },
  {
    id: 'samsunspor',
    name: 'Samsunspor',
    nameLocal: { tr: 'Samsunspor', en: 'Samsunspor', es: 'Samsunspor', pt: 'Samsunspor', fr: 'Samsunspor', de: 'Samsunspor', ar: 'سامسون سبور', it: 'Samsunspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🔴',
    color: '#DC143C',
  },
  {
    id: 'kayserispor',
    name: 'Kayserispor',
    nameLocal: { tr: 'Kayserispor', en: 'Kayserispor', es: 'Kayserispor', pt: 'Kayserispor', fr: 'Kayserispor', de: 'Kayserispor', ar: 'قيصري سبور', it: 'Kayserispor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🟡',
    color: '#FFD700',
  },
  {
    id: 'sivasspor',
    name: 'Sivasspor',
    nameLocal: { tr: 'Sivasspor', en: 'Sivasspor', es: 'Sivasspor', pt: 'Sivasspor', fr: 'Sivasspor', de: 'Sivasspor', ar: 'سيواس سبور', it: 'Sivasspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '⚽',
    color: '#CC0000',
  },
  {
    id: 'gaziantepfk',
    name: 'Gaziantep FK',
    nameLocal: { tr: 'Gaziantep FK', en: 'Gaziantep FK', es: 'Gaziantep FK', pt: 'Gaziantep FK', fr: 'Gaziantep FK', de: 'Gaziantep FK', ar: 'غازي عينتاب', it: 'Gaziantep FK' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🔥',
    color: '#FF0000',
  },
  {
    id: 'adanademirspor',
    name: 'Adana Demirspor',
    nameLocal: { tr: 'Adana Demirspor', en: 'Adana Demirspor', es: 'Adana Demirspor', pt: 'Adana Demirspor', fr: 'Adana Demirspor', de: 'Adana Demirspor', ar: 'أضنة دمير سبور', it: 'Adana Demirspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🔵',
    color: '#003366',
  },
  {
    id: 'rizespor',
    name: 'Rizespor',
    nameLocal: { tr: 'Rizespor', en: 'Rizespor', es: 'Rizespor', pt: 'Rizespor', fr: 'Rizespor', de: 'Rizespor', ar: 'ريزه سبور', it: 'Rizespor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🍵',
    color: '#006633',
  },
  {
    id: 'hatayspor',
    name: 'Hatayspor',
    nameLocal: { tr: 'Hatayspor', en: 'Hatayspor', es: 'Hatayspor', pt: 'Hatayspor', fr: 'Hatayspor', de: 'Hatayspor', ar: 'هاتاي سبور', it: 'Hatayspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🏛️',
    color: '#CC0000',
  },
  {
    id: 'eyupspor',
    name: 'Eyüpspor',
    nameLocal: { tr: 'Eyüpspor', en: 'Eyupspor', es: 'Eyüpspor', pt: 'Eyüpspor', fr: 'Eyüpspor', de: 'Eyüpspor', ar: 'إيوب سبور', it: 'Eyüpspor' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '⚪',
    color: '#FFFFFF',
  },
  {
    id: 'bodrumfk',
    name: 'Bodrum FK',
    nameLocal: { tr: 'Bodrum FK', en: 'Bodrum FK', es: 'Bodrum FK', pt: 'Bodrum FK', fr: 'Bodrum FK', de: 'Bodrum FK', ar: 'بودروم', it: 'Bodrum FK' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '⚓',
    color: '#0066CC',
  },
  {
    id: 'goztepe',
    name: 'Göztepe',
    nameLocal: { tr: 'Göztepe', en: 'Goztepe', es: 'Göztepe', pt: 'Göztepe', fr: 'Göztepe', de: 'Göztepe', ar: 'غوزتبه', it: 'Göztepe' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🟡',
    color: '#FF6600',
  },
  {
    id: 'kayseri',
    name: 'Kayseri',
    nameLocal: { tr: 'Kayseri', en: 'Kayseri', es: 'Kayseri', pt: 'Kayseri', fr: 'Kayseri', de: 'Kayseri', ar: 'قيصري', it: 'Kayseri' },
    league: 'Süper Lig',
    leagueId: 'superlig',
    country: 'Turkey',
    emoji: '🔴',
    color: '#CC0000',
  },

  // ===================== PREMIER LEAGUE =====================
  {
    id: 'mancity',
    name: 'Manchester City',
    nameLocal: { tr: 'Manchester City', en: 'Manchester City', es: 'Manchester City', pt: 'Manchester City', fr: 'Manchester City', de: 'Manchester City', ar: 'مانشستر سيتي', it: 'Manchester City' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🔵',
    color: '#6CABDD',
  },
  {
    id: 'manutd',
    name: 'Manchester United',
    nameLocal: { tr: 'Manchester United', en: 'Manchester United', es: 'Manchester United', pt: 'Manchester United', fr: 'Manchester United', de: 'Manchester United', ar: 'مانشستر يونايتد', it: 'Manchester United' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🔴',
    color: '#DA291C',
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    nameLocal: { tr: 'Arsenal', en: 'Arsenal', es: 'Arsenal', pt: 'Arsenal', fr: 'Arsenal', de: 'Arsenal', ar: 'أرسنال', it: 'Arsenal' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🔴',
    color: '#EF0107',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    nameLocal: { tr: 'Liverpool', en: 'Liverpool', es: 'Liverpool', pt: 'Liverpool', fr: 'Liverpool', de: 'Liverpool', ar: 'ليفربول', it: 'Liverpool' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🔴',
    color: '#C8102E',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    nameLocal: { tr: 'Chelsea', en: 'Chelsea', es: 'Chelsea', pt: 'Chelsea', fr: 'Chelsea', de: 'Chelsea', ar: 'تشيلسي', it: 'Chelsea' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🔵',
    color: '#034694',
  },
  {
    id: 'tottenham',
    name: 'Tottenham',
    nameLocal: { tr: 'Tottenham', en: 'Tottenham Hotspur', es: 'Tottenham', pt: 'Tottenham', fr: 'Tottenham', de: 'Tottenham', ar: 'توتنهام', it: 'Tottenham' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '⚪',
    color: '#132257',
  },
  {
    id: 'newcastle',
    name: 'Newcastle',
    nameLocal: { tr: 'Newcastle', en: 'Newcastle United', es: 'Newcastle', pt: 'Newcastle', fr: 'Newcastle', de: 'Newcastle', ar: 'نيوكاسل', it: 'Newcastle' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '⚫',
    color: '#241F20',
  },
  {
    id: 'astonvilla',
    name: 'Aston Villa',
    nameLocal: { tr: 'Aston Villa', en: 'Aston Villa', es: 'Aston Villa', pt: 'Aston Villa', fr: 'Aston Villa', de: 'Aston Villa', ar: 'أستون فيلا', it: 'Aston Villa' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🟣',
    color: '#95BFE5',
  },
  {
    id: 'brighton',
    name: 'Brighton',
    nameLocal: { tr: 'Brighton', en: 'Brighton & Hove Albion', es: 'Brighton', pt: 'Brighton', fr: 'Brighton', de: 'Brighton', ar: 'برايتون', it: 'Brighton' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '🔵',
    color: '#0057B8',
  },
  {
    id: 'westham',
    name: 'West Ham',
    nameLocal: { tr: 'West Ham', en: 'West Ham United', es: 'West Ham', pt: 'West Ham', fr: 'West Ham', de: 'West Ham', ar: 'وست هام', it: 'West Ham' },
    league: 'Premier League',
    leagueId: 'premier',
    country: 'England',
    emoji: '⚒️',
    color: '#7A263A',
  },

  // ===================== LA LIGA =====================
  {
    id: 'realmadrid',
    name: 'Real Madrid',
    nameLocal: { tr: 'Real Madrid', en: 'Real Madrid', es: 'Real Madrid', pt: 'Real Madrid', fr: 'Real Madrid', de: 'Real Madrid', ar: 'ريال مدريد', it: 'Real Madrid' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '👑',
    color: '#FEBE10',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    nameLocal: { tr: 'Barcelona', en: 'FC Barcelona', es: 'FC Barcelona', pt: 'FC Barcelona', fr: 'FC Barcelone', de: 'FC Barcelona', ar: 'برشلونة', it: 'FC Barcelona' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🔵',
    color: '#A50044',
  },
  {
    id: 'atletico',
    name: 'Atletico Madrid',
    nameLocal: { tr: 'Atletico Madrid', en: 'Atletico Madrid', es: 'Atlético de Madrid', pt: 'Atletico Madrid', fr: 'Atlético Madrid', de: 'Atlético Madrid', ar: 'أتلتيكو مدريد', it: 'Atlético Madrid' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🔴',
    color: '#CB3524',
  },
  {
    id: 'sevilla',
    name: 'Sevilla',
    nameLocal: { tr: 'Sevilla', en: 'Sevilla FC', es: 'Sevilla FC', pt: 'Sevilla FC', fr: 'Séville FC', de: 'FC Sevilla', ar: 'إشبيلية', it: 'Siviglia' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '⚪',
    color: '#D4000D',
  },
  {
    id: 'valencia',
    name: 'Valencia',
    nameLocal: { tr: 'Valencia', en: 'Valencia CF', es: 'Valencia CF', pt: 'Valencia CF', fr: 'Valence CF', de: 'FC Valencia', ar: 'فالنسيا', it: 'Valencia' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🦇',
    color: '#FF7F00',
  },
  {
    id: 'realsociedad',
    name: 'Real Sociedad',
    nameLocal: { tr: 'Real Sociedad', en: 'Real Sociedad', es: 'Real Sociedad', pt: 'Real Sociedad', fr: 'Real Sociedad', de: 'Real Sociedad', ar: 'ريال سوسيداد', it: 'Real Sociedad' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🔵',
    color: '#003DA5',
  },
  {
    id: 'athleticclub',
    name: 'Athletic Club',
    nameLocal: { tr: 'Athletic Club', en: 'Athletic Club', es: 'Athletic Club', pt: 'Athletic Club', fr: 'Athletic Club', de: 'Athletic Bilbao', ar: 'أتلتيك بيلباو', it: 'Athletic Club' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🔴',
    color: '#EE2523',
  },
  {
    id: 'villarreal',
    name: 'Villarreal',
    nameLocal: { tr: 'Villarreal', en: 'Villarreal CF', es: 'Villarreal CF', pt: 'Villarreal CF', fr: 'Villarreal CF', de: 'FC Villarreal', ar: 'فياريال', it: 'Villarreal' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🟡',
    color: '#FFD700',
  },
  {
    id: 'betis',
    name: 'Betis',
    nameLocal: { tr: 'Betis', en: 'Real Betis', es: 'Real Betis', pt: 'Real Betis', fr: 'Real Betis', de: 'Real Betis', ar: 'ريال بيتيس', it: 'Real Betis' },
    league: 'La Liga',
    leagueId: 'laliga',
    country: 'Spain',
    emoji: '🟢',
    color: '#00954C',
  },

  // ===================== BUNDESLIGA =====================
  {
    id: 'bayernmunich',
    name: 'Bayern Munich',
    nameLocal: { tr: 'Bayern Münih', en: 'Bayern Munich', es: 'Bayern Múnich', pt: 'Bayern de Munique', fr: 'Bayern Munich', de: 'FC Bayern München', ar: 'بايرن ميونيخ', it: 'Bayern Monaco' },
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    country: 'Germany',
    emoji: '🔴',
    color: '#DC052D',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    nameLocal: { tr: 'Borussia Dortmund', en: 'Borussia Dortmund', es: 'Borussia Dortmund', pt: 'Borussia Dortmund', fr: 'Borussia Dortmund', de: 'Borussia Dortmund', ar: 'بوروسيا دورتموند', it: 'Borussia Dortmund' },
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    country: 'Germany',
    emoji: '🟡',
    color: '#FDE100',
  },
  {
    id: 'rbleipzig',
    name: 'RB Leipzig',
    nameLocal: { tr: 'RB Leipzig', en: 'RB Leipzig', es: 'RB Leipzig', pt: 'RB Leipzig', fr: 'RB Leipzig', de: 'RB Leipzig', ar: 'آر بي لايبزيغ', it: 'RB Lipsia' },
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    country: 'Germany',
    emoji: '🔴',
    color: '#CC0000',
  },
  {
    id: 'leverkusen',
    name: 'Leverkusen',
    nameLocal: { tr: 'Leverkusen', en: 'Bayer Leverkusen', es: 'Bayer Leverkusen', pt: 'Bayer Leverkusen', fr: 'Bayer Leverkusen', de: 'Bayer 04 Leverkusen', ar: 'باير ليفركوزن', it: 'Bayer Leverkusen' },
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    country: 'Germany',
    emoji: '🔴',
    color: '#E32221',
  },
  {
    id: 'frankfurt',
    name: 'Eintracht Frankfurt',
    nameLocal: { tr: 'Eintracht Frankfurt', en: 'Eintracht Frankfurt', es: 'Eintracht Fráncfort', pt: 'Eintracht Frankfurt', fr: 'Eintracht Francfort', de: 'Eintracht Frankfurt', ar: 'أينتراخت فرانكفورت', it: 'Eintracht Francoforte' },
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    country: 'Germany',
    emoji: '🦅',
    color: '#E1000F',
  },
  {
    id: 'wolfsburg',
    name: 'Wolfsburg',
    nameLocal: { tr: 'Wolfsburg', en: 'VfL Wolfsburg', es: 'VfL Wolfsburgo', pt: 'Wolfsburg', fr: 'Wolfsburg', de: 'VfL Wolfsburg', ar: 'فولفسبورغ', it: 'Wolfsburg' },
    league: 'Bundesliga',
    leagueId: 'bundesliga',
    country: 'Germany',
    emoji: '🐺',
    color: '#65B32E',
  },

  // ===================== SERIE A =====================
  {
    id: 'juventus',
    name: 'Juventus',
    nameLocal: { tr: 'Juventus', en: 'Juventus', es: 'Juventus', pt: 'Juventus', fr: 'Juventus', de: 'Juventus', ar: 'يوفنتوس', it: 'Juventus' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '⚫',
    color: '#000000',
  },
  {
    id: 'inter',
    name: 'Inter Milan',
    nameLocal: { tr: 'Inter Milan', en: 'Inter Milan', es: 'Inter de Milán', pt: 'Inter de Milão', fr: 'Inter Milan', de: 'Inter Mailand', ar: 'إنتر ميلان', it: 'FC Internazionale' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '🔵',
    color: '#010E80',
  },
  {
    id: 'acmilan',
    name: 'AC Milan',
    nameLocal: { tr: 'AC Milan', en: 'AC Milan', es: 'AC Milan', pt: 'AC Milan', fr: 'AC Milan', de: 'AC Mailand', ar: 'ميلان', it: 'AC Milan' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '🔴',
    color: '#FB090B',
  },
  {
    id: 'napoli',
    name: 'Napoli',
    nameLocal: { tr: 'Napoli', en: 'SSC Napoli', es: 'Nápoles', pt: 'Nápoles', fr: 'Naples', de: 'SSC Neapel', ar: 'نابولي', it: 'SSC Napoli' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '🔵',
    color: '#12A0D7',
  },
  {
    id: 'roma',
    name: 'Roma',
    nameLocal: { tr: 'Roma', en: 'AS Roma', es: 'AS Roma', pt: 'AS Roma', fr: 'AS Rome', de: 'AS Rom', ar: 'روما', it: 'AS Roma' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '🐺',
    color: '#8B0000',
  },
  {
    id: 'lazio',
    name: 'Lazio',
    nameLocal: { tr: 'Lazio', en: 'SS Lazio', es: 'SS Lazio', pt: 'SS Lazio', fr: 'SS Lazio', de: 'Lazio Rom', ar: 'لاتسيو', it: 'SS Lazio' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '🦅',
    color: '#87CEEB',
  },
  {
    id: 'fiorentina',
    name: 'Fiorentina',
    nameLocal: { tr: 'Fiorentina', en: 'ACF Fiorentina', es: 'Fiorentina', pt: 'Fiorentina', fr: 'Fiorentina', de: 'Fiorentina', ar: 'فيورنتينا', it: 'ACF Fiorentina' },
    league: 'Serie A',
    leagueId: 'seriea',
    country: 'Italy',
    emoji: '🟣',
    color: '#6A0DAD',
  },

  // ===================== LIGUE 1 =====================
  {
    id: 'psg',
    name: 'PSG',
    nameLocal: { tr: 'PSG', en: 'Paris Saint-Germain', es: 'París Saint-Germain', pt: 'Paris Saint-Germain', fr: 'Paris Saint-Germain', de: 'Paris Saint-Germain', ar: 'باريس سان جيرمان', it: 'Paris Saint-Germain' },
    league: 'Ligue 1',
    leagueId: 'ligue1',
    country: 'France',
    emoji: '🔵',
    color: '#004170',
  },
  {
    id: 'marseille',
    name: 'Marseille',
    nameLocal: { tr: 'Marsilya', en: 'Marseille', es: 'Marsella', pt: 'Marselha', fr: 'Olympique de Marseille', de: 'Marseille', ar: 'مارسيليا', it: 'Marsiglia' },
    league: 'Ligue 1',
    leagueId: 'ligue1',
    country: 'France',
    emoji: '⚪',
    color: '#2CBFEB',
  },
  {
    id: 'lyon',
    name: 'Lyon',
    nameLocal: { tr: 'Lyon', en: 'Olympique Lyonnais', es: 'Olympique de Lyon', pt: 'Lyon', fr: 'Olympique Lyonnais', de: 'Olympique Lyon', ar: 'أولمبيك ليون', it: 'Lione' },
    league: 'Ligue 1',
    leagueId: 'ligue1',
    country: 'France',
    emoji: '🦁',
    color: '#CC0000',
  },
  {
    id: 'monaco',
    name: 'Monaco',
    nameLocal: { tr: 'Monaco', en: 'AS Monaco', es: 'AS Mónaco', pt: 'AS Monaco', fr: 'AS Monaco', de: 'AS Monaco', ar: 'موناكو', it: 'AS Monaco' },
    league: 'Ligue 1',
    leagueId: 'ligue1',
    country: 'France',
    emoji: '🔴',
    color: '#EE2A23',
  },
  {
    id: 'lille',
    name: 'Lille',
    nameLocal: { tr: 'Lille', en: 'LOSC Lille', es: 'Lille OSC', pt: 'Lille', fr: 'Lille OSC', de: 'OSC Lille', ar: 'ليل', it: 'Lille' },
    league: 'Ligue 1',
    leagueId: 'ligue1',
    country: 'France',
    emoji: '🔴',
    color: '#CC0033',
  },
  {
    id: 'nice',
    name: 'Nice',
    nameLocal: { tr: 'Nice', en: 'OGC Nice', es: 'OGC Niza', pt: 'Nice', fr: 'OGC Nice', de: 'OGC Nizza', ar: 'نيس', it: 'OGC Nizza' },
    league: 'Ligue 1',
    leagueId: 'ligue1',
    country: 'France',
    emoji: '🔴',
    color: '#CC0000',
  },

  // ===================== MİLLİ TAKIMLAR =====================
  {
    id: 'turkey',
    name: 'Türkiye',
    nameLocal: { tr: 'Türkiye', en: 'Turkey', es: 'Turquía', pt: 'Turquia', fr: 'Turquie', de: 'Türkei', ar: 'تركيا', it: 'Turchia' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'Turkey',
    emoji: '🇹🇷',
    color: '#E30A17',
  },
  {
    id: 'germany',
    name: 'Almanya',
    nameLocal: { tr: 'Almanya', en: 'Germany', es: 'Alemania', pt: 'Alemanha', fr: 'Allemagne', de: 'Deutschland', ar: 'ألمانيا', it: 'Germania' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'Germany',
    emoji: '🇩🇪',
    color: '#000000',
  },
  {
    id: 'spain',
    name: 'İspanya',
    nameLocal: { tr: 'İspanya', en: 'Spain', es: 'España', pt: 'Espanha', fr: 'Espagne', de: 'Spanien', ar: 'إسبانيا', it: 'Spagna' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'Spain',
    emoji: '🇪🇸',
    color: '#C60B1E',
  },
  {
    id: 'france',
    name: 'Fransa',
    nameLocal: { tr: 'Fransa', en: 'France', es: 'Francia', pt: 'França', fr: 'France', de: 'Frankreich', ar: 'فرنسا', it: 'Francia' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'France',
    emoji: '🇫🇷',
    color: '#002395',
  },
  {
    id: 'england',
    name: 'İngiltere',
    nameLocal: { tr: 'İngiltere', en: 'England', es: 'Inglaterra', pt: 'Inglaterra', fr: 'Angleterre', de: 'England', ar: 'إنجلترا', it: 'Inghilterra' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'England',
    emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    color: '#CF091F',
  },
  {
    id: 'brazil',
    name: 'Brezilya',
    nameLocal: { tr: 'Brezilya', en: 'Brazil', es: 'Brasil', pt: 'Brasil', fr: 'Brésil', de: 'Brasilien', ar: 'البرازيل', it: 'Brasile' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'Brazil',
    emoji: '🇧🇷',
    color: '#009C3B',
  },
  {
    id: 'argentina',
    name: 'Arjantin',
    nameLocal: { tr: 'Arjantin', en: 'Argentina', es: 'Argentina', pt: 'Argentina', fr: 'Argentine', de: 'Argentinien', ar: 'الأرجنتين', it: 'Argentina' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'Argentina',
    emoji: '🇦🇷',
    color: '#74ACDF',
  },
  {
    id: 'portugal',
    name: 'Portekiz',
    nameLocal: { tr: 'Portekiz', en: 'Portugal', es: 'Portugal', pt: 'Portugal', fr: 'Portugal', de: 'Portugal', ar: 'البرتغال', it: 'Portogallo' },
    league: 'Milli Takımlar',
    leagueId: 'national',
    country: 'Portugal',
    emoji: '🇵🇹',
    color: '#006600',
  },

  // ===================== FIFA DÜNYA KUPASI 2026 — TÜM TAKIMLAR =====================
  // Avrupa (UEFA)
  { id: 'belgium',       name: 'Belçika',        nameLocal: { tr: 'Belçika',        en: 'Belgium',       es: 'Bélgica',          pt: 'Bélgica',          fr: 'Belgique',          de: 'Belgien',        ar: 'بلجيكا',                    it: 'Belgio'              }, league: 'Milli Takımlar', leagueId: 'national', country: 'Belgium',        emoji: '🇧🇪', color: '#EF0000' },
  { id: 'netherlands',   name: 'Hollanda',        nameLocal: { tr: 'Hollanda',        en: 'Netherlands',   es: 'Países Bajos',     pt: 'Países Baixos',    fr: 'Pays-Bas',          de: 'Niederlande',    ar: 'هولندا',                    it: 'Paesi Bassi'         }, league: 'Milli Takımlar', leagueId: 'national', country: 'Netherlands',    emoji: '🇳🇱', color: '#FF6700' },
  { id: 'italy',         name: 'İtalya',          nameLocal: { tr: 'İtalya',          en: 'Italy',         es: 'Italia',           pt: 'Itália',           fr: 'Italie',            de: 'Italien',        ar: 'إيطاليا',                   it: 'Italia'              }, league: 'Milli Takımlar', leagueId: 'national', country: 'Italy',          emoji: '🇮🇹', color: '#009246' },
  { id: 'switzerland',   name: 'İsviçre',         nameLocal: { tr: 'İsviçre',         en: 'Switzerland',   es: 'Suiza',            pt: 'Suíça',            fr: 'Suisse',            de: 'Schweiz',        ar: 'سويسرا',                    it: 'Svizzera'            }, league: 'Milli Takımlar', leagueId: 'national', country: 'Switzerland',    emoji: '🇨🇭', color: '#FF0000' },
  { id: 'croatia',       name: 'Hırvatistan',     nameLocal: { tr: 'Hırvatistan',     en: 'Croatia',       es: 'Croacia',          pt: 'Croácia',          fr: 'Croatie',           de: 'Kroatien',       ar: 'كرواتيا',                   it: 'Croazia'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Croatia',        emoji: '🇭🇷', color: '#FF0000' },
  { id: 'norway',        name: 'Norveç',          nameLocal: { tr: 'Norveç',          en: 'Norway',        es: 'Noruega',          pt: 'Noruega',          fr: 'Norvège',           de: 'Norwegen',       ar: 'النرويج',                   it: 'Norvegia'            }, league: 'Milli Takımlar', leagueId: 'national', country: 'Norway',         emoji: '🇳🇴', color: '#EF2B2D' },
  { id: 'austria',       name: 'Avusturya',       nameLocal: { tr: 'Avusturya',       en: 'Austria',       es: 'Austria',          pt: 'Áustria',          fr: 'Autriche',          de: 'Österreich',     ar: 'النمسا',                    it: 'Austria'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Austria',        emoji: '🇦🇹', color: '#ED2939' },
  { id: 'scotland',      name: 'İskoçya',         nameLocal: { tr: 'İskoçya',         en: 'Scotland',      es: 'Escocia',          pt: 'Escócia',          fr: 'Écosse',            de: 'Schottland',     ar: 'اسكتلندا',                  it: 'Scozia'              }, league: 'Milli Takımlar', leagueId: 'national', country: 'Scotland',       emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', color: '#003087' },
  { id: 'czechrepublic', name: 'Çek Cumhuriyeti', nameLocal: { tr: 'Çek Cumhuriyeti', en: 'Czech Republic',es: 'República Checa',  pt: 'República Checa',  fr: 'République tchèque',de: 'Tschechien',     ar: 'جمهورية التشيك',            it: 'Repubblica Ceca'     }, league: 'Milli Takımlar', leagueId: 'national', country: 'Czech Republic', emoji: '🇨🇿', color: '#D7141A' },
  { id: 'bosniaherzegovina', name: 'Bosna-Hersek',  nameLocal: { tr: 'Bosna-Hersek',    en: 'Bosnia-Herzegovina', es: 'Bosnia-Herzegovina', pt: 'Bósnia-Herzegovina', fr: 'Bosnie-Herzégovine', de: 'Bosnien und Herzegowina', ar: 'البوسنة والهرسك', it: 'Bosnia ed Erzegovina' }, league: 'Milli Takımlar', leagueId: 'national', country: 'Bosnia', emoji: '🇧🇦', color: '#002395' },

  // Güney Amerika (CONMEBOL)
  { id: 'colombia',      name: 'Kolombiya',       nameLocal: { tr: 'Kolombiya',       en: 'Colombia',      es: 'Colombia',         pt: 'Colômbia',         fr: 'Colombie',          de: 'Kolumbien',      ar: 'كولومبيا',                  it: 'Colombia'            }, league: 'Milli Takımlar', leagueId: 'national', country: 'Colombia',       emoji: '🇨🇴', color: '#FCD116' },
  { id: 'ecuador',       name: 'Ekvador',         nameLocal: { tr: 'Ekvador',         en: 'Ecuador',       es: 'Ecuador',          pt: 'Equador',          fr: 'Équateur',          de: 'Ecuador',        ar: 'الإكوادور',                 it: 'Ecuador'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Ecuador',        emoji: '🇪🇨', color: '#FFD100' },
  { id: 'uruguay',       name: 'Uruguay',         nameLocal: { tr: 'Uruguay',         en: 'Uruguay',       es: 'Uruguay',          pt: 'Uruguai',          fr: 'Uruguay',           de: 'Uruguay',        ar: 'الأوروغواي',                it: 'Uruguay'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Uruguay',        emoji: '🇺🇾', color: '#75AADB' },
  { id: 'paraguay',      name: 'Paraguay',        nameLocal: { tr: 'Paraguay',        en: 'Paraguay',      es: 'Paraguay',         pt: 'Paraguai',         fr: 'Paraguay',          de: 'Paraguay',       ar: 'باراغواي',                  it: 'Paraguay'            }, league: 'Milli Takımlar', leagueId: 'national', country: 'Paraguay',       emoji: '🇵🇾', color: '#D52B1E' },

  // Kuzey/Orta Amerika (CONCACAF)
  { id: 'mexico',        name: 'Meksika',         nameLocal: { tr: 'Meksika',         en: 'Mexico',        es: 'México',           pt: 'México',           fr: 'Mexique',           de: 'Mexiko',         ar: 'المكسيك',                   it: 'Messico'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Mexico',         emoji: '🇲🇽', color: '#006847' },
  { id: 'canada',        name: 'Kanada',          nameLocal: { tr: 'Kanada',          en: 'Canada',        es: 'Canadá',           pt: 'Canadá',           fr: 'Canada',            de: 'Kanada',         ar: 'كندا',                      it: 'Canada'              }, league: 'Milli Takımlar', leagueId: 'national', country: 'Canada',         emoji: '🇨🇦', color: '#FF0000' },
  { id: 'usa',           name: 'ABD',             nameLocal: { tr: 'ABD',             en: 'USA',           es: 'Estados Unidos',   pt: 'Estados Unidos',   fr: 'États-Unis',        de: 'USA',            ar: 'الولايات المتحدة',          it: 'USA'                 }, league: 'Milli Takımlar', leagueId: 'national', country: 'USA',            emoji: '🇺🇸', color: '#002868' },
  { id: 'haiti',         name: 'Haiti',           nameLocal: { tr: 'Haiti',           en: 'Haiti',         es: 'Haití',            pt: 'Haiti',            fr: 'Haïti',             de: 'Haiti',          ar: 'هايتي',                     it: 'Haiti'               }, league: 'Milli Takımlar', leagueId: 'national', country: 'Haiti',          emoji: '🇭🇹', color: '#00209F' },
  { id: 'curaao',        name: 'Curaçao',         nameLocal: { tr: 'Curaçao',         en: 'Curaçao',       es: 'Curazao',          pt: 'Curaçao',          fr: 'Curaçao',           de: 'Curaçao',        ar: 'كوراساو',                   it: 'Curaçao'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Curaçao',        emoji: '🇨🇼', color: '#002B7F' },

  // Afrika (CAF)
  { id: 'morocco',       name: 'Fas',             nameLocal: { tr: 'Fas',             en: 'Morocco',       es: 'Marruecos',        pt: 'Marrocos',         fr: 'Maroc',             de: 'Marokko',        ar: 'المغرب',                    it: 'Marocco'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Morocco',        emoji: '🇲🇦', color: '#C1272D' },
  { id: 'senegal',       name: 'Senegal',         nameLocal: { tr: 'Senegal',         en: 'Senegal',       es: 'Senegal',          pt: 'Senegal',          fr: 'Sénégal',           de: 'Senegal',        ar: 'السنغال',                   it: 'Senegal'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Senegal',        emoji: '🇸🇳', color: '#00853F' },
  { id: 'ivorycoast',    name: 'Fildişi Sahili',  nameLocal: { tr: 'Fildişi Sahili',  en: 'Ivory Coast',   es: 'Costa de Marfil',  pt: 'Costa do Marfim',  fr: "Côte d'Ivoire",    de: 'Elfenbeinküste', ar: 'ساحل العاج',                it: "Costa d'Avorio"     }, league: 'Milli Takımlar', leagueId: 'national', country: 'Ivory Coast',    emoji: '🇨🇮', color: '#F77F00' },
  { id: 'algeria',       name: 'Cezayir',         nameLocal: { tr: 'Cezayir',         en: 'Algeria',       es: 'Argelia',          pt: 'Argélia',          fr: 'Algérie',           de: 'Algerien',       ar: 'الجزائر',                   it: 'Algeria'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Algeria',        emoji: '🇩🇿', color: '#006233' },
  { id: 'southafrica',   name: 'Güney Afrika',    nameLocal: { tr: 'Güney Afrika',    en: 'South Africa',  es: 'Sudáfrica',        pt: 'África do Sul',    fr: 'Afrique du Sud',    de: 'Südafrika',      ar: 'جنوب أفريقيا',              it: 'Sudafrica'           }, league: 'Milli Takımlar', leagueId: 'national', country: 'South Africa',   emoji: '🇿🇦', color: '#007A4D' },
  { id: 'tunisia',       name: 'Tunus',           nameLocal: { tr: 'Tunus',           en: 'Tunisia',       es: 'Túnez',            pt: 'Tunísia',          fr: 'Tunisie',           de: 'Tunesien',       ar: 'تونس',                      it: 'Tunisia'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Tunisia',        emoji: '🇹🇳', color: '#E70013' },
  { id: 'ghana',         name: 'Gana',            nameLocal: { tr: 'Gana',            en: 'Ghana',         es: 'Ghana',            pt: 'Gana',             fr: 'Ghana',             de: 'Ghana',          ar: 'غانا',                      it: 'Ghana'               }, league: 'Milli Takımlar', leagueId: 'national', country: 'Ghana',          emoji: '🇬🇭', color: '#006B3F' },
  { id: 'nigeria',       name: 'Nijerya',         nameLocal: { tr: 'Nijerya',         en: 'Nigeria',       es: 'Nigeria',          pt: 'Nigéria',          fr: 'Nigéria',           de: 'Nigeria',        ar: 'نيجيريا',                   it: 'Nigeria'             }, league: 'Milli Takımlar', leagueId: 'national', country: 'Nigeria',        emoji: '🇳🇬', color: '#008751' },
  { id: 'egypt',         name: 'Mısır',           nameLocal: { tr: 'Mısır',           en: 'Egypt',         es: 'Egipto',           pt: 'Egito',            fr: 'Égypte',            de: 'Ägypten',        ar: 'مصر',                       it: 'Egitto'              }, league: 'Milli Takımlar', leagueId: 'national', country: 'Egypt',          emoji: '🇪🇬', color: '#C8102E' },
  { id: 'capeverde',     name: 'Yeşil Burun Adaları', nameLocal: { tr: 'Yeşil Burun Adaları', en: 'Cape Verde', es: 'Cabo Verde', pt: 'Cabo Verde', fr: 'Cap-Vert', de: 'Kap Verde', ar: 'الرأس الأخضر', it: 'Capo Verde' }, league: 'Milli Takımlar', leagueId: 'national', country: 'Cape Verde', emoji: '🇨🇻', color: '#003893' },

  // Asya/Okyanusya (AFC + OFC)
  { id: 'japan',         name: 'Japonya',         nameLocal: { tr: 'Japonya',         en: 'Japan',         es: 'Japón',            pt: 'Japão',            fr: 'Japon',             de: 'Japan',          ar: 'اليابان',                   it: 'Giappone'            }, league: 'Milli Takımlar', leagueId: 'national', country: 'Japan',          emoji: '🇯🇵', color: '#BC002D' },
  { id: 'southkorea',    name: 'Güney Kore',      nameLocal: { tr: 'Güney Kore',      en: 'South Korea',   es: 'Corea del Sur',    pt: 'Coreia do Sul',    fr: 'Corée du Sud',      de: 'Südkorea',       ar: 'كوريا الجنوبية',            it: 'Corea del Sud'       }, league: 'Milli Takımlar', leagueId: 'national', country: 'South Korea',    emoji: '🇰🇷', color: '#003478' },
  { id: 'australia',     name: 'Avustralya',      nameLocal: { tr: 'Avustralya',      en: 'Australia',     es: 'Australia',        pt: 'Austrália',        fr: 'Australie',         de: 'Australien',     ar: 'أستراليا',                  it: 'Australia'           }, league: 'Milli Takımlar', leagueId: 'national', country: 'Australia',      emoji: '🇦🇺', color: '#00843D' },
  { id: 'iran',          name: 'İran',            nameLocal: { tr: 'İran',            en: 'Iran',          es: 'Irán',             pt: 'Irã',              fr: 'Iran',              de: 'Iran',           ar: 'إيران',                     it: 'Iran'                }, league: 'Milli Takımlar', leagueId: 'national', country: 'Iran',           emoji: '🇮🇷', color: '#239F40' },
  { id: 'uzbekistan',    name: 'Özbekistan',      nameLocal: { tr: 'Özbekistan',      en: 'Uzbekistan',    es: 'Uzbekistán',       pt: 'Uzbequistão',      fr: 'Ouzbékistan',       de: 'Usbekistan',     ar: 'أوزبكستان',                 it: 'Uzbekistan'          }, league: 'Milli Takımlar', leagueId: 'national', country: 'Uzbekistan',     emoji: '🇺🇿', color: '#1EB53A' },
  { id: 'jordan',        name: 'Ürdün',           nameLocal: { tr: 'Ürdün',           en: 'Jordan',        es: 'Jordania',         pt: 'Jordânia',         fr: 'Jordanie',          de: 'Jordanien',      ar: 'الأردن',                    it: 'Giordania'           }, league: 'Milli Takımlar', leagueId: 'national', country: 'Jordan',         emoji: '🇯🇴', color: '#007A3D' },
  { id: 'qatar',         name: 'Katar',           nameLocal: { tr: 'Katar',           en: 'Qatar',         es: 'Catar',            pt: 'Catar',            fr: 'Qatar',             de: 'Katar',          ar: 'قطر',                       it: 'Qatar'               }, league: 'Milli Takımlar', leagueId: 'national', country: 'Qatar',          emoji: '🇶🇦', color: '#8D1B3D' },
  { id: 'saudiarabia',   name: 'Suudi Arabistan', nameLocal: { tr: 'Suudi Arabistan', en: 'Saudi Arabia',  es: 'Arabia Saudita',   pt: 'Arábia Saudita',   fr: 'Arabie saoudite',   de: 'Saudi-Arabien',  ar: 'المملكة العربية السعودية',  it: 'Arabia Saudita'      }, league: 'Milli Takımlar', leagueId: 'national', country: 'Saudi Arabia',   emoji: '🇸🇦', color: '#006C35' },
  { id: 'newzealand',    name: 'Yeni Zelanda',    nameLocal: { tr: 'Yeni Zelanda',    en: 'New Zealand',   es: 'Nueva Zelanda',    pt: 'Nova Zelândia',    fr: 'Nouvelle-Zélande',  de: 'Neuseeland',     ar: 'نيوزيلندا',                 it: 'Nuova Zelanda'       }, league: 'Milli Takımlar', leagueId: 'national', country: 'New Zealand',    emoji: '🇳🇿', color: '#00247D' },

  // ===================== NBA =====================
  { id: 'lakers',     name: 'LA Lakers',          nameLocal: { tr: 'LA Lakers', en: 'LA Lakers', es: 'LA Lakers', pt: 'LA Lakers', fr: 'LA Lakers', de: 'LA Lakers', ar: 'لوس أنجلوس ليكرز', it: 'LA Lakers' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🟣', color: '#552583', sport: 'basketball' },
  { id: 'warriors',   name: 'Golden State Warriors', nameLocal: { tr: 'Warriors', en: 'Golden State Warriors', es: 'Warriors', pt: 'Warriors', fr: 'Warriors', de: 'Warriors', ar: 'ووريورز', it: 'Warriors' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🔵', color: '#1D428A', sport: 'basketball' },
  { id: 'celtics',    name: 'Boston Celtics',     nameLocal: { tr: 'Celtics', en: 'Boston Celtics', es: 'Celtics', pt: 'Celtics', fr: 'Celtics', de: 'Celtics', ar: 'سيلتيكس', it: 'Celtics' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🟢', color: '#007A33', sport: 'basketball' },
  { id: 'heat',       name: 'Miami Heat',         nameLocal: { tr: 'Miami Heat', en: 'Miami Heat', es: 'Miami Heat', pt: 'Miami Heat', fr: 'Miami Heat', de: 'Miami Heat', ar: 'ميامي هيت', it: 'Miami Heat' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🔴', color: '#98002E', sport: 'basketball' },
  { id: 'bucks',      name: 'Milwaukee Bucks',    nameLocal: { tr: 'Bucks', en: 'Milwaukee Bucks', es: 'Bucks', pt: 'Bucks', fr: 'Bucks', de: 'Bucks', ar: 'باكس', it: 'Bucks' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🟢', color: '#00471B', sport: 'basketball' },
  { id: 'bulls',      name: 'Chicago Bulls',      nameLocal: { tr: 'Bulls', en: 'Chicago Bulls', es: 'Bulls', pt: 'Bulls', fr: 'Bulls', de: 'Bulls', ar: 'بولز', it: 'Bulls' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🔴', color: '#CE1141', sport: 'basketball' },
  { id: 'nuggets',    name: 'Denver Nuggets',     nameLocal: { tr: 'Nuggets', en: 'Denver Nuggets', es: 'Nuggets', pt: 'Nuggets', fr: 'Nuggets', de: 'Nuggets', ar: 'ناجيتس', it: 'Nuggets' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🟡', color: '#0E2240', sport: 'basketball' },
  { id: 'knicks',     name: 'New York Knicks',    nameLocal: { tr: 'Knicks', en: 'New York Knicks', es: 'Knicks', pt: 'Knicks', fr: 'Knicks', de: 'Knicks', ar: 'كنيكس', it: 'Knicks' }, league: 'NBA', leagueId: 'nba', country: 'USA', emoji: '🔵', color: '#F58426', sport: 'basketball' },

  // ===================== EUROLİG / BSL =====================
  { id: 'anadoluefes', name: 'Anadolu Efes',      nameLocal: { tr: 'Anadolu Efes', en: 'Anadolu Efes', es: 'Anadolu Efes', pt: 'Anadolu Efes', fr: 'Anadolu Efes', de: 'Anadolu Efes', ar: 'أناضولو إيفيس', it: 'Anadolu Efes' }, league: 'EuroLeague', leagueId: 'euroleague', country: 'Turkey', emoji: '🔵', color: '#003D7C', sport: 'basketball' },
  { id: 'fenerbahcebeko', name: 'Fenerbahçe Beko', nameLocal: { tr: 'Fenerbahçe Beko', en: 'Fenerbahce Beko', es: 'Fenerbahçe Beko', pt: 'Fenerbahçe Beko', fr: 'Fenerbahçe Beko', de: 'Fenerbahçe Beko', ar: 'فنربخشة بيكو', it: 'Fenerbahçe Beko' }, league: 'EuroLeague', leagueId: 'euroleague', country: 'Turkey', emoji: '🟡', color: '#003D7C', sport: 'basketball' },

  // ===================== VOLEYBOL =====================
  { id: 'halkbank',    name: 'Halkbank',           nameLocal: { tr: 'Halkbank', en: 'Halkbank', es: 'Halkbank', pt: 'Halkbank', fr: 'Halkbank', de: 'Halkbank', ar: 'هالك بانك', it: 'Halkbank' }, league: 'Efeler Ligi', leagueId: 'efeler', country: 'Turkey', emoji: '🟡', color: '#009900', sport: 'volleyball' },
  { id: 'arkas',       name: 'Arkas',              nameLocal: { tr: 'Arkas', en: 'Arkas', es: 'Arkas', pt: 'Arkas', fr: 'Arkas', de: 'Arkas', ar: 'أرقاس', it: 'Arkas' }, league: 'Efeler Ligi', leagueId: 'efeler', country: 'Turkey', emoji: '🔴', color: '#C8102E', sport: 'volleyball' },
  { id: 'ziraatbankkart', name: 'Ziraat Bankkart', nameLocal: { tr: 'Ziraat Bankkart', en: 'Ziraat Bankkart', es: 'Ziraat Bankkart', pt: 'Ziraat Bankkart', fr: 'Ziraat Bankkart', de: 'Ziraat Bankkart', ar: 'زراعت بانكارت', it: 'Ziraat Bankkart' }, league: 'Efeler Ligi', leagueId: 'efeler', country: 'Turkey', emoji: '🔴', color: '#CC0000', sport: 'volleyball' },
  { id: 'vakifbank',   name: 'VakıfBank',          nameLocal: { tr: 'VakıfBank', en: 'VakifBank', es: 'VakıfBank', pt: 'VakıfBank', fr: 'VakıfBank', de: 'VakıfBank', ar: 'واقف بانك', it: 'VakıfBank' }, league: 'Sultansliga', leagueId: 'sultansliga', country: 'Turkey', emoji: '🟡', color: '#F5A623', sport: 'volleyball' },
  { id: 'eczacibasi',  name: 'Eczacıbaşı',         nameLocal: { tr: 'Eczacıbaşı', en: 'Eczacibasi', es: 'Eczacıbaşı', pt: 'Eczacıbaşı', fr: 'Eczacıbaşı', de: 'Eczacıbaşı', ar: 'إجزاجيباشي', it: 'Eczacıbaşı' }, league: 'Sultansliga', leagueId: 'sultansliga', country: 'Turkey', emoji: '🔵', color: '#003087', sport: 'volleyball' },

  // ===================== FORMULA 1 =====================
  { id: 'mercedes_f1',  name: 'Mercedes',          nameLocal: { tr: 'Mercedes', en: 'Mercedes', es: 'Mercedes', pt: 'Mercedes', fr: 'Mercedes', de: 'Mercedes', ar: 'مرسيدس', it: 'Mercedes' }, league: 'Formula 1', leagueId: 'f1', country: 'Germany', emoji: '⬛', color: '#00D2BE', sport: 'motorsport' },
  { id: 'redbull_f1',   name: 'Red Bull',           nameLocal: { tr: 'Red Bull', en: 'Red Bull', es: 'Red Bull', pt: 'Red Bull', fr: 'Red Bull', de: 'Red Bull', ar: 'ريد بول', it: 'Red Bull' }, league: 'Formula 1', leagueId: 'f1', country: 'Austria', emoji: '🔵', color: '#0600EF', sport: 'motorsport' },
  { id: 'ferrari_f1',   name: 'Ferrari',            nameLocal: { tr: 'Ferrari', en: 'Ferrari', es: 'Ferrari', pt: 'Ferrari', fr: 'Ferrari', de: 'Ferrari', ar: 'فيراري', it: 'Ferrari' }, league: 'Formula 1', leagueId: 'f1', country: 'Italy', emoji: '🔴', color: '#DC0000', sport: 'motorsport' },
  { id: 'mclaren_f1',   name: 'McLaren',            nameLocal: { tr: 'McLaren', en: 'McLaren', es: 'McLaren', pt: 'McLaren', fr: 'McLaren', de: 'McLaren', ar: 'ماكلارين', it: 'McLaren' }, league: 'Formula 1', leagueId: 'f1', country: 'UK', emoji: '🟠', color: '#FF8000', sport: 'motorsport' },
  { id: 'astonmartin_f1', name: 'Aston Martin',     nameLocal: { tr: 'Aston Martin', en: 'Aston Martin', es: 'Aston Martin', pt: 'Aston Martin', fr: 'Aston Martin', de: 'Aston Martin', ar: 'أستون مارتن', it: 'Aston Martin' }, league: 'Formula 1', leagueId: 'f1', country: 'UK', emoji: '🟢', color: '#006F62', sport: 'motorsport' },
];

export const getTeamsByLeague = (leagueId: string): Team[] =>
  TEAMS.filter((t) => t.leagueId === leagueId);

export const getTeamById = (id: string): Team | undefined =>
  TEAMS.find((t) => t.id === id);
